name: Terraform Infra Provision

on:
  workflow_dispatch:

jobs:
  plan:
    name: Terraform Plan
    runs-on: ubuntu-latest

    env:
      TF_VAR_hcloud_token: ${{ secrets.HCLOUD_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.HCLOUD_S3_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.HCLOUD_S3_SECRET_KEY }}

    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3

      - run: terraform init -upgrade=false
      - run: terraform validate
      - run: terraform plan -out=tfplan

      - uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: tfplan


  apply:
    name: Terraform Apply
    needs: plan
    runs-on: ubuntu-latest
    environment: infra   # ðŸ‘ˆ This creates pause AFTER plan

    env:
      TF_VAR_hcloud_token: ${{ secrets.HCLOUD_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.HCLOUD_S3_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.HCLOUD_S3_SECRET_KEY }}

    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3

      - run: terraform init -upgrade=false

      - uses: actions/download-artifact@v4
        with:
          name: tfplan

      - run: terraform apply -auto-approve tfplan
      - run: terraform output